FROM openjdk:11
EXPOSE 8000
ADD user/controller/target/microservices-netflix-0.0.1-SNAPSHOT.jar microservices-netflix-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java", "-jar", "/microservices-netflix-0.0.1-SNAPSHOT.jar" ]
