FROM openjdk:11
EXPOSE 8000
WORKDIR user/controller
COPY /target/controller-0.0.1-SNAPSHOT.jar controller-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java", "-jar", "/user/controller/targer/controller-0.0.1-SNAPSHOT.jar" ]
